Sync shell and terminal dotfiles

diff --git a/dot_zshrc.tmpl b/dot_zshrc.tmpl
--- a/dot_zshrc.tmpl
+++ b/dot_zshrc.tmpl
@@ -1,54 +1,116 @@
-# Path to your Oh My Zsh installation.
-export ZSH="$HOME/.oh-my-zsh"
+# zsh options
+setopt AUTO_CD
+setopt CORRECT
+setopt HIST_IGNORE_DUPS
+setopt HIST_IGNORE_SPACE
+setopt SHARE_HISTORY
 
-{{ if hasSuffix "arch" .chezmoi.hostname }}
-ZSH_THEME="arch"
-{{ else }}
-ZSH_THEME="crcandy"
+HISTFILE=~/.zsh_history
+HISTSIZE=10000
+SAVEHIST=10000
+
+# keybindings
+bindkey -e
+bindkey '^f' autosuggest-accept
+
+{{ if eq .chezmoi.os "darwin" }}
+# Homebrew
+eval "$(/opt/homebrew/bin/brew shellenv)"
 {{ end }}
-zstyle ':omz:update' mode reminder
-HIST_STAMPS="dd.mm.yyyy"
-plugins=(git zsh-autosuggestions zsh-syntax-highlighting history-substring-search)
-source $ZSH/oh-my-zsh.sh
 
+# plugins
+if [ -r /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh ]; then
+  source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh
+fi
+if [ -r /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
+  source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
+fi
+ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#6e6a86"
+if [ -r /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
+  source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
+fi
+
+# syntax-highlighting colors, matched to the reference screenshot
+ZSH_HIGHLIGHT_STYLES[command]="fg=#deb6bb"           # known commands: dusty rose
+ZSH_HIGHLIGHT_STYLES[builtin]="fg=#deb6bb"           # builtins
+ZSH_HIGHLIGHT_STYLES[alias]="fg=#deb6bb"             # aliases
+ZSH_HIGHLIGHT_STYLES[function]="fg=#deb6bb"          # shell functions
+ZSH_HIGHLIGHT_STYLES[precommand]="fg=#deb6bb"        # sudo/command/etc
+ZSH_HIGHLIGHT_STYLES[arg0]="fg=#deb6bb"              # first word fallback
+ZSH_HIGHLIGHT_STYLES[unknown-command]="fg=#eb6f92"   # unknown commands: rose/red
+ZSH_HIGHLIGHT_STYLES[path]="fg=#71acca"              # paths: soft blue
+ZSH_HIGHLIGHT_STYLES[globbing]="fg=#f6c177"          # globs: gold
+ZSH_HIGHLIGHT_STYLES[single-quoted-argument]="fg=#a2b0c8"
+ZSH_HIGHLIGHT_STYLES[double-quoted-argument]="fg=#a2b0c8"
+ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]="fg=#f6c177"
+ZSH_HIGHLIGHT_STYLES[comment]="fg=#6e6a86"           # comments/autosuggest muted
+bindkey '^[[A' history-substring-search-up
+bindkey '^[[B' history-substring-search-down
+
+# Starship prompt
+if command -v starship >/dev/null 2>&1; then
+  eval "$(starship init zsh)"
+fi
+
+# Aliases
 source "$HOME/zsh/alias.zsh"
 
 {{ if hasPrefix "REV" .chezmoi.hostname }}
 source "$HOME/zsh/rev.zsh"
 {{ end }}
 
+# GPG
 export GPG_TTY=$(tty)
-export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
 
+# Docker / Colima
+export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
 {{ if eq .chezmoi.os "darwin" }}
 export DOCKER_HOST="unix://${HOME}/.colima/docker.sock"
 {{ end }}
 
 # nvm
 export NVM_DIR="$HOME/.nvm"
-[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
-[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
-
-{{ if eq .chezmoi.os "darwin" }}
-
-# brew
-eval "$(/opt/homebrew/bin/brew shellenv)"
-eval "$(/opt/homebrew/bin/starship init zsh)"
-
-{{ end }}
+[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
 
 # SDKMAN
 export SDKMAN_DIR="$HOME/.sdkman"
 [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
 
-# pipx-created paths
+# PATH
 export PATH="$PATH:$HOME/Library/Python/3.9/bin"
 export PATH="$PATH:$HOME/.local/bin"
+export PATH="$HOME/bin:$PATH"
 export PATH="/Applications/IntelliJ IDEA.app/Contents/MacOS:$PATH"
 export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
 
+# Editors
 export VISUAL="nvim"
 export EDITOR="$VISUAL"
+
+# Android
 export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
 export ANDROID_HOME="$HOME/Library/Android/sdk"
 export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
+
+{{ if eq .chezmoi.os "darwin" }}
+# bun completions
+[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"
+
+# bun
+export BUN_INSTALL="$HOME/.bun"
+export PATH="$BUN_INSTALL/bin:$PATH"
+
+# SSH (Secretive)
+export SSH_AUTH_SOCK="$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh"
+
+# opencode wrapper
+opencode() {
+  local token
+  token="$(gh auth token 2>/dev/null)" || {
+    echo "GitHub auth missing. Run: gh auth login" >&2
+    return 1
+  }
+  GITHUB_PERSONAL_ACCESS_TOKEN="$token" command opencode "$@"
+}
+{{ end }}
